// <auto-generated />
using System;
using LDCT.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LDCT.Api.Data.Migrations
{
    [DbContext(typeof(LdctDbContext))]
    partial class LdctDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LDCT.Api.Data.Entities.FollowUpLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ContactDate")
                        .HasColumnType("date");

                    b.Property<string>("ContactResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HisQuerySummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LinkedSmsMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousSnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackCorridor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "ContactDate");

                    b.ToTable("FollowUpLogs");
                });

            modelBuilder.Entity("LDCT.Api.Data.Entities.IntegrationSettingRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("IntegrationSettings");
                });

            modelBuilder.Entity("LDCT.Api.Data.Entities.LdctCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CaseManagerNarrativeNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChestClinicOneMonth")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClosedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClosureCode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DiagnosisDate")
                        .HasColumnType("date");

                    b.Property<bool>("DiagnosisRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("DiagnosisStage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalReportQueryUrlTemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasNodule")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("LdctStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LlmNeedsReview")
                        .HasColumnType("bit");

                    b.Property<string>("LlmRawOutputJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlmVerifiedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxNoduleLengthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NeedOutpatientFollowUp")
                        .HasColumnType("bit");

                    b.Property<int?>("NoduleCount")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReportLanded")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ReportLandedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReportNarrativeSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Track1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Track12Months")
                        .HasColumnType("bit");

                    b.Property<string>("Track2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Track3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Track3Months")
                        .HasColumnType("bit");

                    b.Property<string>("Track4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Track6Months")
                        .HasColumnType("bit");

                    b.Property<string>("TrackType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordNumber")
                        .IsUnique();

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LDCT.Api.Data.Entities.OrphanLdctReportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("OrphanLdctReports");
                });

            modelBuilder.Entity("LDCT.Api.Data.Entities.SmsMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("SmsMessages");
                });

            modelBuilder.Entity("LDCT.Api.Data.Entities.FollowUpLogEntry", b =>
                {
                    b.HasOne("LDCT.Api.Data.Entities.LdctCase", "Case")
                        .WithMany("FollowUpLogs")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LDCT.Api.Data.Entities.SmsMessage", b =>
                {
                    b.HasOne("LDCT.Api.Data.Entities.LdctCase", "Case")
                        .WithMany("SmsMessages")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LDCT.Api.Data.Entities.LdctCase", b =>
                {
                    b.Navigation("FollowUpLogs");

                    b.Navigation("SmsMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
